BEGIN;

UPDATE public.produk_provider_map
SET kode_provider = CASE UPPER(TRIM(kode_provider))
  WHEN 'WALLET_PPOB:DANA' THEN 'DANA'
  WHEN 'WALLET_PPOB:OVO' THEN 'OVO'
  WHEN 'WALLET_PPOB:GOPAY' THEN 'GOPAY'
  WHEN 'WALLET_PPOB:SHOPEEPAY' THEN 'SHOPEEPAY'
  WHEN 'WALLET_PPOB:LINKAJA' THEN 'LINKAJA'
  WHEN 'DIRECT:ELDN' THEN 'ELDN'
  WHEN 'DIRECT:GPYOPEN' THEN 'GPYOPEN'
  WHEN 'DIRECT:SHPOPEN' THEN 'SHPOPEN'
  WHEN 'DIRECT:ELOV' THEN 'ELOV'
  WHEN 'DIRECT:ELLI' THEN 'ELLI'
  ELSE kode_provider
END,
    diubah_pada = NOW()
WHERE LOWER(TRIM(provider)) = 'smb'
  AND UPPER(TRIM(kode_provider)) IN (
    'WALLET_PPOB:DANA',
    'WALLET_PPOB:OVO',
    'WALLET_PPOB:GOPAY',
    'WALLET_PPOB:SHOPEEPAY',
    'WALLET_PPOB:LINKAJA',
    'DIRECT:ELDN',
    'DIRECT:GPYOPEN',
    'DIRECT:SHPOPEN',
    'DIRECT:ELOV',
    'DIRECT:ELLI'
  );

COMMIT;
