package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/joho/godotenv"

	"pulsa2/javapay"
	ridgen "pulsa2/refid"
)

func promptString(reader *bufio.Reader, label, defaultValue string) string {
	fmt.Printf("%s", label)
	if strings.TrimSpace(defaultValue) != "" {
		fmt.Printf(" [%s]", defaultValue)
	}
	fmt.Print(": ")

	line, err := reader.ReadString('\n')
	if err != nil {
		return strings.TrimSpace(defaultValue)
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return strings.TrimSpace(defaultValue)
	}
	return line
}

func promptInt64(reader *bufio.Reader, label string, defaultValue int64) int64 {
	for {
		raw := promptString(reader, label, strconv.FormatInt(defaultValue, 10))
		n, err := strconv.ParseInt(strings.TrimSpace(raw), 10, 64)
		if err == nil && n > 0 {
			return n
		}
		fmt.Println("input harus angka dan > 0")
	}
}

func envOrDefault(key, fallback string) string {
	v := strings.TrimSpace(os.Getenv(key))
	if v != "" {
		return v
	}
	return strings.TrimSpace(fallback)
}

func normalizeJavaPayBaseURL(v string) string {
	v = strings.TrimSpace(v)
	v = strings.TrimRight(v, "/")
	v = strings.TrimSuffix(v, "/trx")
	return v
}

func main() {
	_ = godotenv.Load(".env")

	baseURLFlag := flag.String("baseurl", "https://api.javapay.id/api/trx", "base URL JavaPay")
	command := flag.String("cmd", "PAY", "JavaPay command (PAY/INQ/STATUS)")
	dest := flag.String("dest", "085711910503", "destination/tujuan (default: 085711910503)")
	qty := flag.Int64("qty", 10000, "qty/nominal")
	refid := flag.String("refid", "", "refid (optional, default autogenerated)")
	product := flag.String("product", "DNID", "kode produk (default DANA)")
	memberCodeFlag := flag.String("member-code", "P24J00001", "member code JavaPay")
	apiKeyFlag := flag.String("apikey", "aeaaef70d1274958ebdfb3a3d0d831ea0630c980d6f91712451cde4c4eda3afa", "API key JavaPay udah di hardcode enter aja")
	pinFlag := flag.String("pin", "238710", "PIN JavaPay skip aja udah di hardcode")
	timeout := flag.Duration("timeout", 20*time.Second, "request timeout")
	flag.Parse()

	reader := bufio.NewReader(os.Stdin)

	cmd := strings.ToUpper(strings.TrimSpace(*command))
	if cmd == "" {
		cmd = strings.ToUpper(promptString(reader, "Masukan command", "PAY"))
	}

	baseURL := strings.TrimSpace(*baseURLFlag)
	if baseURL == "" {
		baseURL = "https://api.javapay.id/api/trx"
	}
	baseURL = normalizeJavaPayBaseURL(promptString(reader, "Masukan base URL Javapay", baseURL))

	destVal := strings.TrimSpace(*dest)
	qtyVal := *qty
	productVal := strings.TrimSpace(*product)
	if cmd != "STATUS" && cmd != "STATUS-PAY" {
		destVal = promptString(reader, "Masukan tujuan", destVal)
		if destVal == "" {
			log.Fatal("dest is required, contoh: -dest 081234567890")
		}

		qtyVal = promptInt64(reader, "Masukan nominal/qty", *qty)
		if qtyVal <= 0 {
			log.Fatal("qty must be > 0")
		}

		if productVal == "" {
			productVal = promptString(reader, "Masukan kode produk", "DANA")
		}
	}

	refIDVal := strings.TrimSpace(*refid)
	refIDVal = promptString(reader, "Masukan refid", refIDVal)

	memberCode := promptString(reader, "Masukan member code Javapay", envOrDefault("JAVAPAY_MEMBERID", *memberCodeFlag))
	if memberCode == "" {
		log.Fatal("member code javapay wajib diisi")
	}
	apiKey := promptString(reader, "Masukan API key Javapay", envOrDefault("JAVAPAY_APIKEY", *apiKeyFlag))
	if apiKey == "" {
		log.Fatal("api key javapay wajib diisi")
	}
	pin := promptString(reader, "Masukan PIN Javapay", envOrDefault("JAVAPAY_PIN", *pinFlag))
	if pin == "" {
		log.Fatal("pin javapay wajib diisi")
	}

	client := javapay.New(baseURL, memberCode, apiKey, pin, *timeout)

	rid := strings.TrimSpace(refIDVal)
	if rid == "" {
		rid = ridgen.Generate("JP")
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	var (
		resp       map[string]any
		httpStatus int
		reqBody    map[string]any
		err        error
	)
	switch cmd {
	case "STATUS", "STATUS-PAY":
		resp, httpStatus, reqBody, err = client.Status(ctx, rid)
	default:
		resp, httpStatus, reqBody, err = client.Trx(
			ctx,
			cmd,
			productVal,
			destVal,
			qtyVal,
			rid,
		)
	}
	if err != nil {
		log.Fatalf("javapay trx error: %v", err)
	}

	fmt.Println("=== REQUEST ===")
	fmt.Printf("base_url  : %s\n", baseURL)
	fmt.Printf("member_id : %s\n", memberCode)
	fmt.Printf("command   : %s\n", cmd)
	fmt.Printf("product   : %s\n", productVal)
	fmt.Printf("dest      : %s\n", destVal)
	fmt.Printf("qty       : %d\n", qtyVal)
	fmt.Printf("refid     : %s\n", rid)
	fmt.Printf("req_body  : %#v\n", reqBody)

	fmt.Println("\n=== RESPONSE ===")
	fmt.Printf("http_status: %d\n", httpStatus)
	fmt.Printf("body       : %#v\n", resp)
}
