package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/joho/godotenv"

	ridgen "pulsa2/refid"
	"pulsa2/yuscom"
)

func mustEnv(key string) string {
	v := strings.TrimSpace(os.Getenv(key))
	if v == "" {
		log.Fatalf("missing required env: %s", key)
	}
	return v
}

func main() {
	_ = godotenv.Load(".env")

	product := flag.String("product", "DANA", "kode produk Yuscom (contoh: DANA)")
	dest := flag.String("dest", "085711910503", "destination/tujuan (default: 085711910503)")
	qty := flag.Int64("qty", 10000, "qty/nominal")
	refid := flag.String("refid", "", "refid (optional, default autogenerated)")
	timeout := flag.Duration("timeout", 20*time.Second, "request timeout")
	flag.Parse()

	if strings.TrimSpace(*dest) == "" {
		log.Fatal("dest is required, contoh: -dest 081234567890")
	}
	if *qty <= 0 {
		log.Fatal("qty must be > 0")
	}

	baseURL := mustEnv("YUSCOM_BASE_URL")
	memberID := mustEnv("YUSCOM_MEMBERID")
	pin := mustEnv("YUSCOM_PIN")
	password := mustEnv("YUSCOM_PASSWORD")

	client := yuscom.New(baseURL, memberID, pin, password, *timeout)

	rid := strings.TrimSpace(*refid)
	if rid == "" {
		rid = ridgen.Generate("YS")
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	acc, httpStatus, body, err := client.TrxNoSign(
		ctx,
		strings.TrimSpace(*product),
		*qty,
		strings.TrimSpace(*dest),
		rid,
	)
	if err != nil {
		log.Fatalf("yuscom trx error: %v", err)
	}

	fmt.Println("=== REQUEST ===")
	fmt.Printf("base_url  : %s\n", baseURL)
	fmt.Printf("member_id : %s\n", memberID)
	fmt.Printf("product   : %s\n", strings.TrimSpace(*product))
	fmt.Printf("dest      : %s\n", strings.TrimSpace(*dest))
	fmt.Printf("qty       : %d\n", *qty)
	fmt.Printf("refid     : %s\n", rid)

	fmt.Println("\n=== RESPONSE ===")
	fmt.Printf("http_status: %d\n", httpStatus)
	fmt.Printf("body       : %s\n", body)
	fmt.Printf("parsed.ref : %s\n", acc.RefID)
	fmt.Printf("parsed.tkt : %s\n", acc.Ticket)
	fmt.Printf("parsed.price: %d\n", acc.Price)
}
